#!/bin/bash

LOG_FILE="/tmp/gpu-hooks-$(date +%s).log"

if [[ $1 == "win11" ]]; then
	case "$2" in
        	"prepare")
                {
			echo "[$(date)] === PREPARE START ==="
			rc-service libvirt-inhibit start
			rc-service disks-manager stop
			/usr/local/bin/gpu-detach.sh
			echo "[$(date)] === PREPARE END ==="
                } 2>&1 | tee "$LOG_FILE"
                ;;

                "release")
                {
			echo "[$(date)] === RELEASE START ==="
			rc-service libvirt-inhibit stop
			rc-service disks-manager start
			/usr/local/bin/gpu-reattach.sh
			echo "[$(date)] === RELEASE END ==="
                } 2>&1 | tee "$LOG_FILE"
                ;;
	esac
fi
